#!/usr/bin/perl
use strict;     #wymagaj inicjalizacji zmiennej przed użyciem
use warnings;   #wypisuj informacje

#wypisz pomoc
sub printHelp
{
	print("Oto pomoc nadchodzi!\n");
}

my $argsCount = @ARGV;
if($argsCount == 0)
{
    printHelp();
    exit -1;
}
print "Jest $argsCount argumentów z $0\n";
